export const BUSINESS = {
  name: 'Elegant Brows & Wax',
  shortName: 'Elegant',
  monogram: 'EB',
  tagline: 'Define Your Beauty. Enhance Your Confidence.',
  taglineBeats: ['Define Your Beauty', 'Enhance Your Confidence'],
  pitch: 'Expert threading, waxing & premium facials — by appointment.',
  phone: '647-613-1675',
  email: 'elegantbrowswax@gmail.com',
  instagram: '__elegant_brows__wax',
  instagramUrl: 'https://www.instagram.com/__elegant_brows__wax',
  address: {
    street: 'By Appointment Only',
    city: 'Toronto',
    province: 'ON',
    full: 'Toronto, ON',
  },
  hours: [
    { day: 'Monday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Tuesday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Wednesday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Thursday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Friday', hours: '10:00 AM – 7:00 PM' },
    { day: 'Saturday', hours: '10:00 AM – 6:00 PM' },
    { day: 'Sunday', hours: '11:00 AM – 5:00 PM' },
  ],
  appointmentsOnly: true,
  founded: 2020,
}
