/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LocationRouteImport } from './routes/location'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesUpperLipWaxRouteImport } from './routes/services.upper-lip-wax'
import { Route as ServicesUpperLipThreadingRouteImport } from './routes/services.upper-lip-threading'
import { Route as ServicesUnderarmsWaxRouteImport } from './routes/services.underarms-wax'
import { Route as ServicesStomachWaxRouteImport } from './routes/services.stomach-wax'
import { Route as ServicesRedWineFacialRouteImport } from './routes/services.red-wine-facial'
import { Route as ServicesO3RadianceFacialRouteImport } from './routes/services.o3-radiance-facial'
import { Route as ServicesLusterGoldFacialRouteImport } from './routes/services.luster-gold-facial'
import { Route as ServicesKoreanGlassFacialRouteImport } from './routes/services.korean-glass-facial'
import { Route as ServicesHydraBoostFacialRouteImport } from './routes/services.hydra-boost-facial'
import { Route as ServicesHalfArmsLegsWaxRouteImport } from './routes/services.half-arms-legs-wax'
import { Route as ServicesFullFaceWaxRouteImport } from './routes/services.full-face-wax'
import { Route as ServicesFullFaceThreadingRouteImport } from './routes/services.full-face-threading'
import { Route as ServicesFullBodyWaxRouteImport } from './routes/services.full-body-wax'
import { Route as ServicesFullArmsLegsWaxRouteImport } from './routes/services.full-arms-legs-wax'
import { Route as ServicesForeheadThreadingRouteImport } from './routes/services.forehead-threading'
import { Route as ServicesEyebrowWaxRouteImport } from './routes/services.eyebrow-wax'
import { Route as ServicesEyebrowThreadingRouteImport } from './routes/services.eyebrow-threading'
import { Route as ServicesCleanUpJellyMaskRouteImport } from './routes/services.clean-up-jelly-mask'
import { Route as ServicesChinWaxRouteImport } from './routes/services.chin-wax'
import { Route as ServicesBackWaxRouteImport } from './routes/services.back-wax'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUpperLipWaxRoute = ServicesUpperLipWaxRouteImport.update({
  id: '/upper-lip-wax',
  path: '/upper-lip-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUpperLipThreadingRoute =
  ServicesUpperLipThreadingRouteImport.update({
    id: '/upper-lip-threading',
    path: '/upper-lip-threading',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesUnderarmsWaxRoute = ServicesUnderarmsWaxRouteImport.update({
  id: '/underarms-wax',
  path: '/underarms-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesStomachWaxRoute = ServicesStomachWaxRouteImport.update({
  id: '/stomach-wax',
  path: '/stomach-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRedWineFacialRoute = ServicesRedWineFacialRouteImport.update({
  id: '/red-wine-facial',
  path: '/red-wine-facial',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesO3RadianceFacialRoute =
  ServicesO3RadianceFacialRouteImport.update({
    id: '/o3-radiance-facial',
    path: '/o3-radiance-facial',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLusterGoldFacialRoute =
  ServicesLusterGoldFacialRouteImport.update({
    id: '/luster-gold-facial',
    path: '/luster-gold-facial',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesKoreanGlassFacialRoute =
  ServicesKoreanGlassFacialRouteImport.update({
    id: '/korean-glass-facial',
    path: '/korean-glass-facial',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHydraBoostFacialRoute =
  ServicesHydraBoostFacialRouteImport.update({
    id: '/hydra-boost-facial',
    path: '/hydra-boost-facial',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHalfArmsLegsWaxRoute = ServicesHalfArmsLegsWaxRouteImport.update({
  id: '/half-arms-legs-wax',
  path: '/half-arms-legs-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullFaceWaxRoute = ServicesFullFaceWaxRouteImport.update({
  id: '/full-face-wax',
  path: '/full-face-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullFaceThreadingRoute =
  ServicesFullFaceThreadingRouteImport.update({
    id: '/full-face-threading',
    path: '/full-face-threading',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesFullBodyWaxRoute = ServicesFullBodyWaxRouteImport.update({
  id: '/full-body-wax',
  path: '/full-body-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFullArmsLegsWaxRoute = ServicesFullArmsLegsWaxRouteImport.update({
  id: '/full-arms-legs-wax',
  path: '/full-arms-legs-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesForeheadThreadingRoute =
  ServicesForeheadThreadingRouteImport.update({
    id: '/forehead-threading',
    path: '/forehead-threading',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesEyebrowWaxRoute = ServicesEyebrowWaxRouteImport.update({
  id: '/eyebrow-wax',
  path: '/eyebrow-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEyebrowThreadingRoute =
  ServicesEyebrowThreadingRouteImport.update({
    id: '/eyebrow-threading',
    path: '/eyebrow-threading',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCleanUpJellyMaskRoute =
  ServicesCleanUpJellyMaskRouteImport.update({
    id: '/clean-up-jelly-mask',
    path: '/clean-up-jelly-mask',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesChinWaxRoute = ServicesChinWaxRouteImport.update({
  id: '/chin-wax',
  path: '/chin-wax',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBackWaxRoute = ServicesBackWaxRouteImport.update({
  id: '/back-wax',
  path: '/back-wax',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/back-wax': typeof ServicesBackWaxRoute
  '/services/chin-wax': typeof ServicesChinWaxRoute
  '/services/clean-up-jelly-mask': typeof ServicesCleanUpJellyMaskRoute
  '/services/eyebrow-threading': typeof ServicesEyebrowThreadingRoute
  '/services/eyebrow-wax': typeof ServicesEyebrowWaxRoute
  '/services/forehead-threading': typeof ServicesForeheadThreadingRoute
  '/services/full-arms-legs-wax': typeof ServicesFullArmsLegsWaxRoute
  '/services/full-body-wax': typeof ServicesFullBodyWaxRoute
  '/services/full-face-threading': typeof ServicesFullFaceThreadingRoute
  '/services/full-face-wax': typeof ServicesFullFaceWaxRoute
  '/services/half-arms-legs-wax': typeof ServicesHalfArmsLegsWaxRoute
  '/services/hydra-boost-facial': typeof ServicesHydraBoostFacialRoute
  '/services/korean-glass-facial': typeof ServicesKoreanGlassFacialRoute
  '/services/luster-gold-facial': typeof ServicesLusterGoldFacialRoute
  '/services/o3-radiance-facial': typeof ServicesO3RadianceFacialRoute
  '/services/red-wine-facial': typeof ServicesRedWineFacialRoute
  '/services/stomach-wax': typeof ServicesStomachWaxRoute
  '/services/underarms-wax': typeof ServicesUnderarmsWaxRoute
  '/services/upper-lip-threading': typeof ServicesUpperLipThreadingRoute
  '/services/upper-lip-wax': typeof ServicesUpperLipWaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services/back-wax': typeof ServicesBackWaxRoute
  '/services/chin-wax': typeof ServicesChinWaxRoute
  '/services/clean-up-jelly-mask': typeof ServicesCleanUpJellyMaskRoute
  '/services/eyebrow-threading': typeof ServicesEyebrowThreadingRoute
  '/services/eyebrow-wax': typeof ServicesEyebrowWaxRoute
  '/services/forehead-threading': typeof ServicesForeheadThreadingRoute
  '/services/full-arms-legs-wax': typeof ServicesFullArmsLegsWaxRoute
  '/services/full-body-wax': typeof ServicesFullBodyWaxRoute
  '/services/full-face-threading': typeof ServicesFullFaceThreadingRoute
  '/services/full-face-wax': typeof ServicesFullFaceWaxRoute
  '/services/half-arms-legs-wax': typeof ServicesHalfArmsLegsWaxRoute
  '/services/hydra-boost-facial': typeof ServicesHydraBoostFacialRoute
  '/services/korean-glass-facial': typeof ServicesKoreanGlassFacialRoute
  '/services/luster-gold-facial': typeof ServicesLusterGoldFacialRoute
  '/services/o3-radiance-facial': typeof ServicesO3RadianceFacialRoute
  '/services/red-wine-facial': typeof ServicesRedWineFacialRoute
  '/services/stomach-wax': typeof ServicesStomachWaxRoute
  '/services/underarms-wax': typeof ServicesUnderarmsWaxRoute
  '/services/upper-lip-threading': typeof ServicesUpperLipThreadingRoute
  '/services/upper-lip-wax': typeof ServicesUpperLipWaxRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/location': typeof LocationRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/back-wax': typeof ServicesBackWaxRoute
  '/services/chin-wax': typeof ServicesChinWaxRoute
  '/services/clean-up-jelly-mask': typeof ServicesCleanUpJellyMaskRoute
  '/services/eyebrow-threading': typeof ServicesEyebrowThreadingRoute
  '/services/eyebrow-wax': typeof ServicesEyebrowWaxRoute
  '/services/forehead-threading': typeof ServicesForeheadThreadingRoute
  '/services/full-arms-legs-wax': typeof ServicesFullArmsLegsWaxRoute
  '/services/full-body-wax': typeof ServicesFullBodyWaxRoute
  '/services/full-face-threading': typeof ServicesFullFaceThreadingRoute
  '/services/full-face-wax': typeof ServicesFullFaceWaxRoute
  '/services/half-arms-legs-wax': typeof ServicesHalfArmsLegsWaxRoute
  '/services/hydra-boost-facial': typeof ServicesHydraBoostFacialRoute
  '/services/korean-glass-facial': typeof ServicesKoreanGlassFacialRoute
  '/services/luster-gold-facial': typeof ServicesLusterGoldFacialRoute
  '/services/o3-radiance-facial': typeof ServicesO3RadianceFacialRoute
  '/services/red-wine-facial': typeof ServicesRedWineFacialRoute
  '/services/stomach-wax': typeof ServicesStomachWaxRoute
  '/services/underarms-wax': typeof ServicesUnderarmsWaxRoute
  '/services/upper-lip-threading': typeof ServicesUpperLipThreadingRoute
  '/services/upper-lip-wax': typeof ServicesUpperLipWaxRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/back-wax'
    | '/services/chin-wax'
    | '/services/clean-up-jelly-mask'
    | '/services/eyebrow-threading'
    | '/services/eyebrow-wax'
    | '/services/forehead-threading'
    | '/services/full-arms-legs-wax'
    | '/services/full-body-wax'
    | '/services/full-face-threading'
    | '/services/full-face-wax'
    | '/services/half-arms-legs-wax'
    | '/services/hydra-boost-facial'
    | '/services/korean-glass-facial'
    | '/services/luster-gold-facial'
    | '/services/o3-radiance-facial'
    | '/services/red-wine-facial'
    | '/services/stomach-wax'
    | '/services/underarms-wax'
    | '/services/upper-lip-threading'
    | '/services/upper-lip-wax'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services/back-wax'
    | '/services/chin-wax'
    | '/services/clean-up-jelly-mask'
    | '/services/eyebrow-threading'
    | '/services/eyebrow-wax'
    | '/services/forehead-threading'
    | '/services/full-arms-legs-wax'
    | '/services/full-body-wax'
    | '/services/full-face-threading'
    | '/services/full-face-wax'
    | '/services/half-arms-legs-wax'
    | '/services/hydra-boost-facial'
    | '/services/korean-glass-facial'
    | '/services/luster-gold-facial'
    | '/services/o3-radiance-facial'
    | '/services/red-wine-facial'
    | '/services/stomach-wax'
    | '/services/underarms-wax'
    | '/services/upper-lip-threading'
    | '/services/upper-lip-wax'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/location'
    | '/reviews'
    | '/services'
    | '/services/back-wax'
    | '/services/chin-wax'
    | '/services/clean-up-jelly-mask'
    | '/services/eyebrow-threading'
    | '/services/eyebrow-wax'
    | '/services/forehead-threading'
    | '/services/full-arms-legs-wax'
    | '/services/full-body-wax'
    | '/services/full-face-threading'
    | '/services/full-face-wax'
    | '/services/half-arms-legs-wax'
    | '/services/hydra-boost-facial'
    | '/services/korean-glass-facial'
    | '/services/luster-gold-facial'
    | '/services/o3-radiance-facial'
    | '/services/red-wine-facial'
    | '/services/stomach-wax'
    | '/services/underarms-wax'
    | '/services/upper-lip-threading'
    | '/services/upper-lip-wax'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  LocationRoute: typeof LocationRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/upper-lip-wax': {
      id: '/services/upper-lip-wax'
      path: '/upper-lip-wax'
      fullPath: '/services/upper-lip-wax'
      preLoaderRoute: typeof ServicesUpperLipWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/upper-lip-threading': {
      id: '/services/upper-lip-threading'
      path: '/upper-lip-threading'
      fullPath: '/services/upper-lip-threading'
      preLoaderRoute: typeof ServicesUpperLipThreadingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/underarms-wax': {
      id: '/services/underarms-wax'
      path: '/underarms-wax'
      fullPath: '/services/underarms-wax'
      preLoaderRoute: typeof ServicesUnderarmsWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/stomach-wax': {
      id: '/services/stomach-wax'
      path: '/stomach-wax'
      fullPath: '/services/stomach-wax'
      preLoaderRoute: typeof ServicesStomachWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/red-wine-facial': {
      id: '/services/red-wine-facial'
      path: '/red-wine-facial'
      fullPath: '/services/red-wine-facial'
      preLoaderRoute: typeof ServicesRedWineFacialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/o3-radiance-facial': {
      id: '/services/o3-radiance-facial'
      path: '/o3-radiance-facial'
      fullPath: '/services/o3-radiance-facial'
      preLoaderRoute: typeof ServicesO3RadianceFacialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/luster-gold-facial': {
      id: '/services/luster-gold-facial'
      path: '/luster-gold-facial'
      fullPath: '/services/luster-gold-facial'
      preLoaderRoute: typeof ServicesLusterGoldFacialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/korean-glass-facial': {
      id: '/services/korean-glass-facial'
      path: '/korean-glass-facial'
      fullPath: '/services/korean-glass-facial'
      preLoaderRoute: typeof ServicesKoreanGlassFacialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hydra-boost-facial': {
      id: '/services/hydra-boost-facial'
      path: '/hydra-boost-facial'
      fullPath: '/services/hydra-boost-facial'
      preLoaderRoute: typeof ServicesHydraBoostFacialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/half-arms-legs-wax': {
      id: '/services/half-arms-legs-wax'
      path: '/half-arms-legs-wax'
      fullPath: '/services/half-arms-legs-wax'
      preLoaderRoute: typeof ServicesHalfArmsLegsWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-face-wax': {
      id: '/services/full-face-wax'
      path: '/full-face-wax'
      fullPath: '/services/full-face-wax'
      preLoaderRoute: typeof ServicesFullFaceWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-face-threading': {
      id: '/services/full-face-threading'
      path: '/full-face-threading'
      fullPath: '/services/full-face-threading'
      preLoaderRoute: typeof ServicesFullFaceThreadingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-body-wax': {
      id: '/services/full-body-wax'
      path: '/full-body-wax'
      fullPath: '/services/full-body-wax'
      preLoaderRoute: typeof ServicesFullBodyWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/full-arms-legs-wax': {
      id: '/services/full-arms-legs-wax'
      path: '/full-arms-legs-wax'
      fullPath: '/services/full-arms-legs-wax'
      preLoaderRoute: typeof ServicesFullArmsLegsWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/forehead-threading': {
      id: '/services/forehead-threading'
      path: '/forehead-threading'
      fullPath: '/services/forehead-threading'
      preLoaderRoute: typeof ServicesForeheadThreadingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/eyebrow-wax': {
      id: '/services/eyebrow-wax'
      path: '/eyebrow-wax'
      fullPath: '/services/eyebrow-wax'
      preLoaderRoute: typeof ServicesEyebrowWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/eyebrow-threading': {
      id: '/services/eyebrow-threading'
      path: '/eyebrow-threading'
      fullPath: '/services/eyebrow-threading'
      preLoaderRoute: typeof ServicesEyebrowThreadingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/clean-up-jelly-mask': {
      id: '/services/clean-up-jelly-mask'
      path: '/clean-up-jelly-mask'
      fullPath: '/services/clean-up-jelly-mask'
      preLoaderRoute: typeof ServicesCleanUpJellyMaskRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/chin-wax': {
      id: '/services/chin-wax'
      path: '/chin-wax'
      fullPath: '/services/chin-wax'
      preLoaderRoute: typeof ServicesChinWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/back-wax': {
      id: '/services/back-wax'
      path: '/back-wax'
      fullPath: '/services/back-wax'
      preLoaderRoute: typeof ServicesBackWaxRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesBackWaxRoute: typeof ServicesBackWaxRoute
  ServicesChinWaxRoute: typeof ServicesChinWaxRoute
  ServicesCleanUpJellyMaskRoute: typeof ServicesCleanUpJellyMaskRoute
  ServicesEyebrowThreadingRoute: typeof ServicesEyebrowThreadingRoute
  ServicesEyebrowWaxRoute: typeof ServicesEyebrowWaxRoute
  ServicesForeheadThreadingRoute: typeof ServicesForeheadThreadingRoute
  ServicesFullArmsLegsWaxRoute: typeof ServicesFullArmsLegsWaxRoute
  ServicesFullBodyWaxRoute: typeof ServicesFullBodyWaxRoute
  ServicesFullFaceThreadingRoute: typeof ServicesFullFaceThreadingRoute
  ServicesFullFaceWaxRoute: typeof ServicesFullFaceWaxRoute
  ServicesHalfArmsLegsWaxRoute: typeof ServicesHalfArmsLegsWaxRoute
  ServicesHydraBoostFacialRoute: typeof ServicesHydraBoostFacialRoute
  ServicesKoreanGlassFacialRoute: typeof ServicesKoreanGlassFacialRoute
  ServicesLusterGoldFacialRoute: typeof ServicesLusterGoldFacialRoute
  ServicesO3RadianceFacialRoute: typeof ServicesO3RadianceFacialRoute
  ServicesRedWineFacialRoute: typeof ServicesRedWineFacialRoute
  ServicesStomachWaxRoute: typeof ServicesStomachWaxRoute
  ServicesUnderarmsWaxRoute: typeof ServicesUnderarmsWaxRoute
  ServicesUpperLipThreadingRoute: typeof ServicesUpperLipThreadingRoute
  ServicesUpperLipWaxRoute: typeof ServicesUpperLipWaxRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBackWaxRoute: ServicesBackWaxRoute,
  ServicesChinWaxRoute: ServicesChinWaxRoute,
  ServicesCleanUpJellyMaskRoute: ServicesCleanUpJellyMaskRoute,
  ServicesEyebrowThreadingRoute: ServicesEyebrowThreadingRoute,
  ServicesEyebrowWaxRoute: ServicesEyebrowWaxRoute,
  ServicesForeheadThreadingRoute: ServicesForeheadThreadingRoute,
  ServicesFullArmsLegsWaxRoute: ServicesFullArmsLegsWaxRoute,
  ServicesFullBodyWaxRoute: ServicesFullBodyWaxRoute,
  ServicesFullFaceThreadingRoute: ServicesFullFaceThreadingRoute,
  ServicesFullFaceWaxRoute: ServicesFullFaceWaxRoute,
  ServicesHalfArmsLegsWaxRoute: ServicesHalfArmsLegsWaxRoute,
  ServicesHydraBoostFacialRoute: ServicesHydraBoostFacialRoute,
  ServicesKoreanGlassFacialRoute: ServicesKoreanGlassFacialRoute,
  ServicesLusterGoldFacialRoute: ServicesLusterGoldFacialRoute,
  ServicesO3RadianceFacialRoute: ServicesO3RadianceFacialRoute,
  ServicesRedWineFacialRoute: ServicesRedWineFacialRoute,
  ServicesStomachWaxRoute: ServicesStomachWaxRoute,
  ServicesUnderarmsWaxRoute: ServicesUnderarmsWaxRoute,
  ServicesUpperLipThreadingRoute: ServicesUpperLipThreadingRoute,
  ServicesUpperLipWaxRoute: ServicesUpperLipWaxRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  LocationRoute: LocationRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
